import { Button, Container, Link } from '@chakra-ui/react'
import axios from 'axios'
import { useRouter } from 'next/dist/client/router';
import Head from 'next/head'
import { useEffect, useState } from 'react';
import { authStore } from '../store/auth-store';

export default function LandingPage() {
  const [loggedIn, setLoggedIn] = useState(false)
  const router = useRouter()

  useEffect(() => {
    authStore.subscribe(() => setLoggedIn(authStore.getState().loggedIn))
    console.log('Use effect called')
    if (loggedIn) {
      router.push('/home')
    }
  })

  return (
    <>
      <Head>
        <title>GiftXTrade - Gift Exchange, Secret Santa Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container mt='5' mb='5'>
        <Link href='http://localhost:3001/auth/google'>
          <Button>Login with Google</Button>
        </Link>
      </Container>
    </>
  )
}
