import { Button, Container, Link } from '@chakra-ui/react'
import axios from 'axios'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>GiftXTrade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container mt='5' mb='5'>
        <Link href='http://localhost:3001/auth/google'>
          <Button >Login with Google</Button>
        </Link>
      </Container>
    </>
  )
}
