import { Text, Heading, Container, Box, Image, Link } from '@chakra-ui/react'
import Head from 'next/head';
import { PrivacySection } from '../components/PrivacySection';
import NextLink from 'next/link';

export default function Privacy() {
  return (
    <>
      <Head>
        <title>Privacy and Terms of Service - GiftTrade</title>
      </Head>

      <Container pt='10' pb='10' maxW='2xl'>
        <Box mb='14'>
          <NextLink href='/' passHref>
            <Link display="inline-block">
              <Image w='40' src='/logos/logotype_rounded_color.svg' quality='90' />
            </Link>
          </NextLink>
        </Box>

        <Box mb='5'>
          <Heading size='lg'>Privacy and Terms of Service</Heading>
          <Text><small>Version: July 17, 2021</small></Text>
        </Box>

        <Box>

          <PrivacySection
            heading={null}
            text={[
              <Text>
                GiftTrade is a free service that aims to make it easy for friends and family with creating and managing gift exchange events.
              </Text>,
              <Text>
                Our team at GiftTrade takes user's privacy extremely seriously. As a result, we make sure to clearly explain how GiftTrade displays, manages, and stores user data. We also make sure to only store the most minimal amount of data to make GiftTrade work faster and provide a reliable service.
              </Text>
            ]}
            textSpacing={5}
          />

          <br />
          <br />

          <PrivacySection
            heading="Your privacy"
            text={[
              <Text>
                Due to the nature of how users join GiftTrade, it is required for them to log in using Google. GiftTrade only stores the user's first and last name, email, and profile picture. We do not store any tokens or keys generated by Google on our database. Additionally, we use the Google Maps API to get convert the user’s current location to a readable format and we store this information to help other participants with shipping and mailing packages. Addresses are stored securely and can only be seen by participants that are also in the same event.
              </Text>,
              <Text>
                We do not share any of the user data with any other company or organization. All of the user’s data mentioned above is stored in order to provide a better user experience.
              </Text>
            ]}
          />

          <br />
          <br />

          <PrivacySection
            heading='Data Deletion/Removal'
            text={[
              <Text>
                All organizers have the ability to permanently delete an event. Upon deletion, all related data such as the participant’s draws, addresses, wish lists are all deleted from our database.
              </Text>,
              <Text>
                Additionally, all participants have the ability to leave an event, doing so will remove their address for the event and all their wish lists for the specific event.
              </Text>
            ]}
          />

          <br />
          <br />

          <PrivacySection
            heading='Amazon Products'
            text={[
              <Text>
                All products on the GiftTrade wishlist/store are fetched from Amazon, as GiftTrade is part of the <Link href='https://affiliate-program.amazon.com/' isExternal={true} color='blue.500'>Amazon Affiliate Program</Link>. This means that when a user buys a product from the store, Amazon owes a certain percentage of their profit to GiftTrade. The end-user is not affected by this in any way, and this is solely to help run GiftTrade.
              </Text>,
            ]}
          />

          <br />
          <br />

          <PrivacySection
            heading='Google Analytics'
            text={[
              <Text>In order for GiftTrade to check the effectiveness of our online marketing and increase user support for various platforms, GiftTrade uses <Link href='https://marketingplatform.google.com/about/analytics/' isExternal={true} color='blue.500'>Google Analytics</Link> to gain insight on the website traffic which helps us determine spikes in traffic so we can spawn servers as needed. As a result, you are also subject to the terms and privacy conditions of Google Analytics. For more information about Google Analytics terms <Link href='https://marketingplatform.google.com/about/analytics/terms/us/' isExternal={true} color='blue.500'>click here</Link>.</Text>,
            ]}
          />

        </Box>
      </Container>
    </>
  )
}